# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  -  id: trailing-whitespace
  -  id: end-of-file-fixer
  -  id: check-yaml
  -  id: check-added-large-files

- repo: https://github.com/ambv/black
  rev: 21.10b0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a4
  hooks:
  - id: pylint
