name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # GitHub VM should already have Python 3.8
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install and Build
        run: |
          jupyter-book build mynewbook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: mynewbook/_build/html
