name: Coverage
on:
  [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m coverage run -m unittest discover tests/

      - name: Show coverage
        run: |
          python -m coverage report --show-missing

      - name: Run Coveralls
        run: |
          coveralls --service=github
