name: Test
on:
  [pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      # Will run unit tests and generate code coverage
      - name: pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Run Coveralls
        run: |
          coveralls
