name: Coverage
on:
  [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      # Will run our tests with coverage for us
      - name: pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Show coverage
        run: |
          python -m coverage report --show-missing

      - name: Run Coveralls
        run: |
          coveralls --service=github
